import type { Mission } from "./missions";

// Business & Operations (10) + Finance & Banking (9).
export const MISSIONS_BIZ: Mission[] = [
  {
    id: "seed-hrbp", slug: "hrbp-analisis-turnover-tech", roleId: "hr-business-partner",
    titleId: "Analisis Turnover Divisi Tech + Rencana Retensi",
    briefId: "Turnover divisi Tech 24% YoY. Dari dataset anonim (tenure, dept, performance, exit reason): buat spreadsheet analisis (pivot + chart) + dokumen 2 halaman insight + 3 intervensi prioritas dengan biaya & timeline.",
    deliverableSpec: { modes: ["DOCUMENT", "SPREADSHEET", "LINK"], minArtifacts: 2, constraints: "Wajib pivot + chart + 3 intervensi berbiaya" },
    rubric: [
      { id: "analisis", labelId: "Ketepatan analisis data turnover", weight: 0.35 },
      { id: "insight", labelId: "Kedalaman insight & segmentasi", weight: 0.3 },
      { id: "rencana", labelId: "Kelayakan rencana retensi", weight: 0.35 },
    ],
    skkniUnitCode: "SKKNI-HR-U2", kkniLevel: 6, difficulty: 3, estimatedMin: 150, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-recruiter", slug: "recruiter-sourcing-backend-7hari", roleId: "hr-recruiter",
    titleId: "Rencana Sourcing Backend Dev dalam 7 Hari",
    briefId: "Hiring manager butuh 2 backend dev dalam 30 hari. Buat: Boolean search strings (3 platform), screening scorecard, template pesan outreach (ID + EN), dan funnel plan (berapa profil → screen → interview) + tracker spreadsheet.",
    deliverableSpec: { modes: ["DOCUMENT", "SPREADSHEET", "LINK"], minArtifacts: 2, constraints: "Wajib scorecard + funnel numbers" },
    rubric: [
      { id: "sourcing", labelId: "Kualitas strategi sourcing", weight: 0.35 },
      { id: "screening", labelId: "Ketepatan scorecard & filter", weight: 0.35 },
      { id: "funnel", labelId: "Realisme funnel & timeline", weight: 0.3 },
    ],
    skkniUnitCode: "SKKNI-HR-U1", kkniLevel: 5, difficulty: 2, estimatedMin: 120, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-ae", slug: "ae-proposal-b2b-saas", roleId: "account-executive",
    titleId: "Proposal B2B SaaS + Simulasi Negosiasi Diskon",
    briefId: "Prospek retail (50 toko) minta proposal kasir SaaS + diskon 40%. Buat proposal 2 halaman (scope, harga, SLA) + spreadsheet simulasi 3 skenario diskon vs margin + script negosiasi (pembuka, handle objeksi harga, closing) + ajukan harga final yang kamu pertahankan.",
    deliverableSpec: { modes: ["DOCUMENT", "SPREADSHEET"], minArtifacts: 2, constraints: "Wajib simulasi margin + harga final" },
    rubric: [
      { id: "proposal", labelId: "Kualitas proposal & value prop", weight: 0.35 },
      { id: "angka", labelId: "Ketepatan simulasi harga-margin", weight: 0.35 },
      { id: "negosiasi", labelId: "Kualitas strategi negosiasi", weight: 0.3 },
    ],
    skkniUnitCode: "SKKNI-SALES-U2", kkniLevel: 5, difficulty: 3, estimatedMin: 150, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-mt", slug: "mt-proyek-efisiensi-gerai", roleId: "management-trainee",
    titleId: "Proyek Efisiensi Gerai + Presentasi ke Direksi",
    briefId: "20 gerai, biaya lembur naik 30%. Analisis data anonim (jam sibuk, staffing, omzet/jam) → 3 hipotesis → 1 pilot plan 30 hari (2 gerai) → deck 5 slide untuk direksi (masalah, data, rekomendasi, risiko, minta keputusan).",
    deliverableSpec: { modes: ["DOCUMENT", "SPREADSHEET", "LINK"], minArtifacts: 2, constraints: "Wajib deck 5 slide + pilot plan" },
    rubric: [
      { id: "analisis", labelId: "Ketajaman analisis & hipotesis", weight: 0.4 },
      { id: "pilot", labelId: "Kelayakan pilot 30 hari", weight: 0.3 },
      { id: "deck", labelId: "Kualitas deck eksekutif", weight: 0.3 },
    ],
    skkniUnitCode: "SKKNI-PM-U2", kkniLevel: 6, difficulty: 4, estimatedMin: 180, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-ops", slug: "ops-sop-gudang-lebaran", roleId: "operations-executive",
    titleId: "SOP Lonjakan Order 5x Jelang Lebaran",
    briefId: "Order naik 5x 2 minggu sebelum Lebaran; gudang + armada pas-pasan. Tulis SOP 2 halaman (shift, prioritas picking, buffer stok) + spreadsheet kapasitas (orang, jam, paket/hari) + escalation matrix + 3 KPI harian.",
    deliverableSpec: { modes: ["DOCUMENT", "SPREADSHEET"], minArtifacts: 2, constraints: "Wajib hitungan kapasitas + eskalasi" },
    rubric: [
      { id: "sop", labelId: "Kelengkapan & kejelasan SOP", weight: 0.4 },
      { id: "kapasitas", labelId: "Akurasi hitungan kapasitas", weight: 0.35 },
      { id: "kpi", labelId: "Ketepatan KPI & eskalasi", weight: 0.25 },
    ],
    skkniUnitCode: "SKKNI-OPS-U1", kkniLevel: 5, difficulty: 3, estimatedMin: 150, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-cs", slug: "cs-playbook-komplain-viral", roleId: "customer-success",
    titleId: "Playbook Komplain Viral + Template Respons",
    briefId: "Chatbot memberi harga 30% lebih murah ke 200 user; screenshot viral. Buat playbook: segmentasi user, 3 template respons (WA, sosmed, email), kebijakan kompensasi bertingkat + spreadsheet estimasi biaya, dan langkah cegah ulang.",
    deliverableSpec: { modes: ["DOCUMENT", "SPREADSHEET"], minArtifacts: 2, constraints: "Wajib 3 template + estimasi biaya" },
    rubric: [
      { id: "empati", labelId: "Empati & ketepatan nada respons", weight: 0.35 },
      { id: "kebijakan", labelId: "Keadilan kebijakan kompensasi", weight: 0.35 },
      { id: "pencegahan", labelId: "Kualitas pencegahan ulang", weight: 0.3 },
    ],
    skkniUnitCode: "SKKNI-CS-U1", kkniLevel: 5, difficulty: 2, estimatedMin: 120, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-procurement", slug: "procurement-evaluasi-tender-laptop", roleId: "procurement-staff",
    titleId: "Evaluasi Tender Laptop Rp800 Juta",
    briefId: "3 vendor menawar pengadaan laptop. Dari matriks anonim (harga, garansi, spek, rekam jejak): buat spreadsheet scoring terbobot + rekomendasi pemenang + minutes of meeting + daftar dokumen yang wajib dilengkapi + catatan etika (menolak titipan).",
    deliverableSpec: { modes: ["SPREADSHEET", "DOCUMENT"], minArtifacts: 2, constraints: "Wajib scoring terbobot + rekomendasi" },
    rubric: [
      { id: "skoring", labelId: "Ketepatan metode scoring", weight: 0.4 },
      { id: "rekomendasi", labelId: "Kualitas justifikasi pemenang", weight: 0.35 },
      { id: "etika", labelId: "Kepatuhan etika pengadaan", weight: 0.25 },
    ],
    skkniUnitCode: "SKKNI-PROC-U1", kkniLevel: 5, difficulty: 3, estimatedMin: 150, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-retail", slug: "retail-shift-plan-toko-baru", roleId: "retail-store-supervisor",
    titleId: "Shift Plan + Target Toko Baru 30 Hari",
    briefId: "Toko baru 8 staff, target Rp300jt/bulan. Buat roster 4 minggu (shift, libur, peak coverage) + breakdown target per orang + checklist opening-closing + 1 halaman cara handle komplain di tempat.",
    deliverableSpec: { modes: ["SPREADSHEET", "DOCUMENT"], minArtifacts: 2, constraints: "Wajib roster 4 minggu + breakdown target" },
    rubric: [
      { id: "roster", labelId: "Keadilan & cakupan roster", weight: 0.4 },
      { id: "target", labelId: "Realisme breakdown target", weight: 0.35 },
      { id: "layanan", labelId: "Kualitas standar layanan", weight: 0.25 },
    ],
    skkniUnitCode: "SKKNI-RTL-U1", kkniLevel: 5, difficulty: 2, estimatedMin: 120, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-mgmt-cons", slug: "mgmtcons-profitability-sawit", roleId: "management-consultant",
    titleId: "Analisis Profitabilitas + Deck 5 Slide",
    briefId: "Klien kebun sawit margin turun 5 tahun. Dari data anonim: buat issue tree, analisis 3 hipotesis (harga, yield, biaya) dalam spreadsheet + deck 5 slide (SO WHAT per slide) + 1 halaman next steps.",
    deliverableSpec: { modes: ["DOCUMENT", "SPREADSHEET"], minArtifacts: 2, constraints: "Wajib issue tree + SO WHAT" },
    rubric: [
      { id: "struktur", labelId: "Ketajaman struktur (MECE)", weight: 0.4 },
      { id: "analisis", labelId: "Kedalaman analisis angka", weight: 0.35 },
      { id: "storyline", labelId: "Kualitas storyline deck", weight: 0.25 },
    ],
    skkniUnitCode: "SKKNI-CONS-U1", kkniLevel: 6, difficulty: 5, estimatedMin: 240, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-corpstrat", slug: "corpstrat-ekspansi-kota-baru", roleId: "corporate-strategy-analyst",
    titleId: "Studi Ekspansi 3 Kota + Model Sederhana",
    briefId: "Ritel mau ekspansi ke 3 kota. Buat spreadsheet scoring kota (populasi, daya beli, sewa, kompetitor) + model P&L 1 tahun per kota + memo 2 halaman (rekomendasi urutan buka + risiko) + 3 skenario (base/optimis/pesimis).",
    deliverableSpec: { modes: ["SPREADSHEET", "DOCUMENT"], minArtifacts: 2, constraints: "Wajib 3 skenario + rekomendasi" },
    rubric: [
      { id: "model", labelId: "Kualitas model & asumsi", weight: 0.4 },
      { id: "rekomendasi", labelId: "Ketajaman rekomendasi", weight: 0.35 },
      { id: "risiko", labelId: "Kelengkapan risiko & skenario", weight: 0.25 },
    ],
    skkniUnitCode: "SKKNI-STRAT-U1", kkniLevel: 6, difficulty: 5, estimatedMin: 240, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-jr-acct", slug: "jracct-laporan-umkm-ppn", roleId: "junior-accountant",
    titleId: "Laporan Keuangan UMKM + Hitung PPN",
    briefId: "UMKM kuliner omzet Rp80jt/bulan, pencatatan campur. Dari mutasi anonim: susun laba-rugi + neraca sederhana + hitung PPN terutang + daftar koreksi/bukti yang kurang + checklist e-Faktur.",
    deliverableSpec: { modes: ["SPREADSHEET", "DOCUMENT"], minArtifacts: 2, constraints: "Wajib L/R + neraca + PPN" },
    rubric: [
      { id: "laporan", labelId: "Akurasi laporan keuangan", weight: 0.4 },
      { id: "pajak", labelId: "Ketepatan hitung PPN", weight: 0.35 },
      { id: "rapi", labelId: "Kelengkapan koreksi & bukti", weight: 0.25 },
    ],
    skkniUnitCode: "M.691090.001.01", kkniLevel: 6, difficulty: 3, estimatedMin: 180, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-teller", slug: "teller-edukasi-nasabah-aman", roleId: "teller-bank",
    titleId: "Simulasi Teller: Nasabah Panik + Edukasi Anti-Fraud",
    briefId: "Nasabah lansia panik: diminta transfer oleh 'bank' via telepon. Tulis SOP respons di counter (langkah 1–7) + script edukasi 1 menit + brosur 1 halaman ciri penipuan + cara eskalasi ke CSO/security.",
    deliverableSpec: { modes: ["DOCUMENT", "IMAGE"], minArtifacts: 1, constraints: "Wajib script + eskalasi" },
    rubric: [
      { id: "sop", labelId: "Ketepatan SOP & kepatuhan", weight: 0.4 },
      { id: "edukasi", labelId: "Kejelasan edukasi nasabah", weight: 0.35 },
      { id: "empati", labelId: "Empati & ketenangan", weight: 0.25 },
    ],
    skkniUnitCode: "SKKNI-BANK-U1", kkniLevel: 5, difficulty: 2, estimatedMin: 90, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-credit", slug: "credit-memo-umkm-500jt", roleId: "credit-analyst",
    titleId: "Memo Kredit UMKM Rp500 Juta (5C)",
    briefId: "Pengajuan KUR Rp500jt untuk ekspansi waralaba minuman. Dari laporan keuangan + BI checking anonim: tulis memo 2 halaman (5C, DSCR, agunan, rekomendasi: setuju/bersyarat/tolak + covenant) + spreadsheet DSCR.",
    deliverableSpec: { modes: ["DOCUMENT", "SPREADSHEET"], minArtifacts: 2, constraints: "Wajib DSCR + rekomendasi eksplisit" },
    rubric: [
      { id: "analisis", labelId: "Kedalaman analisis 5C", weight: 0.4 },
      { id: "angka", labelId: "Akurasi DSCR & agunan", weight: 0.35 },
      { id: "keputusan", labelId: "Keberanian & dasar keputusan", weight: 0.25 },
    ],
    skkniUnitCode: "SKKNI-BANK-U2", kkniLevel: 6, difficulty: 4, estimatedMin: 180, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-finplan", slug: "finplan-keluarga-muda-10thn", roleId: "financial-planner",
    titleId: "Rencana Keuangan Keluarga Muda 10 Tahun",
    briefId: "Pasangan 28th, income Rp18jt/bln, 1 anak, KPR. Buat: cashflow + dana darurat + asuransi need analysis + alokasi investasi (profil moderat) + spreadsheet proyeksi 10 tahun + 1 halaman 'yang TIDAK boleh dibeli'.",
    deliverableSpec: { modes: ["SPREADSHEET", "DOCUMENT"], minArtifacts: 2, constraints: "Wajib need analysis + proyeksi" },
    rubric: [
      { id: "cashflow", labelId: "Kesehatan struktur cashflow", weight: 0.35 },
      { id: "proteksi", labelId: "Ketepatan kebutuhan proteksi", weight: 0.35 },
      { id: "investasi", labelId: "Kesesuaian alokasi profil risiko", weight: 0.3 },
    ],
    skkniUnitCode: "SKKNI-FP-U1", kkniLevel: 5, difficulty: 3, estimatedMin: 180, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-investment", slug: "investment-memo-series-a", roleId: "investment-analyst",
    titleId: "Memo Investasi Startup Series A",
    briefId: "Startup logistik dingin minta Rp40M. Dari deck + data anonim: tulis memo 3 halaman (tesis, unit economics, valuasi comps sederhana, risiko, rekomendasi + syarat) + cap table pro-forma.",
    deliverableSpec: { modes: ["DOCUMENT", "SPREADSHEET"], minArtifacts: 2, constraints: "Wajib unit economics + rekomendasi" },
    rubric: [
      { id: "tesis", labelId: "Ketajaman tesis investasi", weight: 0.35 },
      { id: "angka", labelId: "Kualitas analisis valuasi", weight: 0.4 },
      { id: "risiko", labelId: "Kejujuran membahas risiko", weight: 0.25 },
    ],
    skkniUnitCode: "SKKNI-INV-U1", kkniLevel: 6, difficulty: 5, estimatedMin: 240, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-actuarial", slug: "actuarial-premi-asuransi-mikro", roleId: "actuarial-associate",
    titleId: "Pricing Asuransi Mikro + Tabel Premi",
    briefId: "Perusahaan mau produk asuransi mikro premi <Rp50rb/bln. Dari tabel mortalitas + klaim anonim: hitung premi murni + loading + tabel premi per usia + 1 halaman asumsi & sensitivitas + catatan solvabilitas.",
    deliverableSpec: { modes: ["SPREADSHEET", "DOCUMENT"], minArtifacts: 2, constraints: "Wajib tabel premi + asumsi" },
    rubric: [
      { id: "teknis", labelId: "Ketepatan perhitungan aktuaria", weight: 0.45 },
      { id: "asumsi", labelId: "Kejelasan asumsi & sensitivitas", weight: 0.3 },
      { id: "bisnis", labelId: "Kelayakan premi vs pasar", weight: 0.25 },
    ],
    skkniUnitCode: "SKKNI-ACT-U1", kkniLevel: 6, difficulty: 5, estimatedMin: 240, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-auditor", slug: "auditor-temuan-kas-kecil", roleId: "external-auditor",
    titleId: "Kertas Kerja Audit Kas Kecil + Temuan",
    briefId: "Dari mutasi kas kecil 3 bulan anonim: buat kertas kerja (sampling, vouching, selisih) + daftar 5 temuan berperingkat (kritis–rendah) + rekomendasi pengendalian + draft management letter 1 halaman.",
    deliverableSpec: { modes: ["SPREADSHEET", "DOCUMENT"], minArtifacts: 2, constraints: "Wajib 5 temuan berperingkat" },
    rubric: [
      { id: "prosedur", labelId: "Ketepatan prosedur audit", weight: 0.4 },
      { id: "temuan", labelId: "Kualitas temuan & peringkat", weight: 0.35 },
      { id: "rekomendasi", labelId: "Kegunaan rekomendasi kontrol", weight: 0.25 },
    ],
    skkniUnitCode: "M.691090.007.01", kkniLevel: 6, difficulty: 4, estimatedMin: 180, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-tax", slug: "tax-spt-konsultan-freelance", roleId: "tax-consultant",
    titleId: "SPT Konsultan Freelance + Koreksi Fiskal",
    briefId: "Freelancer IT penghasilan Rp600jt/thn, banyak biaya campur. Susun: rekonsiliasi fiskal + hitung PPh terutang (NPPN vs pembukuan) + daftar bukti kurang + 1 halaman strategi legal (bukan akal-akalan) + checklist lapor.",
    deliverableSpec: { modes: ["SPREADSHEET", "DOCUMENT"], minArtifacts: 2, constraints: "Wajib rekonsiliasi + PPh" },
    rubric: [
      { id: "hitung", labelId: "Akurasi perhitungan pajak", weight: 0.45 },
      { id: "bukti", labelId: "Kelengkapan koreksi & bukti", weight: 0.3 },
      { id: "etika", labelId: "Kepatuhan & kehati-hatian", weight: 0.25 },
    ],
    skkniUnitCode: "M.691090.005.01", kkniLevel: 6, difficulty: 4, estimatedMin: 180, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-treasury", slug: "treasury-likuiditas-lebaran", roleId: "treasury-analyst",
    titleId: "Forecast Likuiditas 13 Minggu + Hedging FX",
    briefId: "Importir bayar supplier USD tiap bulan. Buat rolling forecast 13 minggu (inflow/outflow, buffer) + analisis 2 opsi hedging (forward vs natural hedge) + rekomendasi + dashboard 1 halaman untuk CFO.",
    deliverableSpec: { modes: ["SPREADSHEET", "DOCUMENT"], minArtifacts: 2, constraints: "Wajib forecast + rekomendasi hedge" },
    rubric: [
      { id: "forecast", labelId: "Akurasi struktur forecast", weight: 0.4 },
      { id: "hedge", labelId: "Kualitas analisis hedging", weight: 0.35 },
      { id: "komunikasi", labelId: "Kejelasan dashboard CFO", weight: 0.25 },
    ],
    skkniUnitCode: "SKKNI-TRS-U1", kkniLevel: 6, difficulty: 4, estimatedMin: 180, maxRevisions: 3, status: "PUBLISHED",
  },
];
