import type { Mission } from "./missions";

// Creative & Marketing (14).
export const MISSIONS_CREATIVE: Mission[] = [
  {
    id: "seed-sosmed", slug: "sosmed-kalender-konten-30-hari", roleId: "social-media-specialist",
    titleId: "Kalender Konten 30 Hari + Budget Meta Ads",
    briefId: "Brand F&B lokal launching menu baru. Buat kalender 30 hari (12 feed, 8 reels, 10 story series) + pilar konten + caption draft 3 posting + alokasi budget Meta Ads Rp5jt/bulan dengan proyeksi reach/CTR + 1 contoh visual.",
    deliverableSpec: { modes: ["DOCUMENT", "SPREADSHEET", "IMAGE", "LINK"], minArtifacts: 2, constraints: "Wajib budget table + 3 caption draft" },
    rubric: [
      { id: "relevansi", labelId: "Relevansi terhadap brief & audiens lokal", weight: 0.3 },
      { id: "struktur", labelId: "Struktur kalender & konsistensi pilar", weight: 0.25 },
      { id: "budget", labelId: "Realisme budget & proyeksi metrics", weight: 0.25 },
      { id: "kualitas", labelId: "Kualitas caption & visual", weight: 0.2 },
    ],
    skkniUnitCode: "M.70MKT00.012.1", kkniLevel: 5, difficulty: 2, estimatedMin: 120, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-uiux", slug: "uiux-redesign-checkout-umkm", roleId: "ui-ux-designer",
    titleId: "Redesign Checkout UMKM + Case Study",
    briefId: "Checkout UMKM drop-off 70%. Dari screenshot alur saat ini: buat case study 1–2 halaman (temuan usability, 3 perbaikan prioritas) + wireframe/link Figma alur baru + alasan tiap perubahan + plan usability test 5 user.",
    deliverableSpec: { modes: ["DOCUMENT", "LINK", "IMAGE"], minArtifacts: 2, constraints: "Wajib wireframe + test plan" },
    rubric: [
      { id: "temuan", labelId: "Ketajaman temuan usability", weight: 0.35 },
      { id: "solusi", labelId: "Kualitas solusi desain", weight: 0.4 },
      { id: "validasi", labelId: "Kualitas rencana validasi", weight: 0.25 },
    ],
    skkniUnitCode: "M.70MKT00.014.1", kkniLevel: 5, difficulty: 3, estimatedMin: 180, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-creator", slug: "creator-7-hari-launching-minuman", roleId: "content-creator-agency",
    titleId: "7 Konten Launching Minuman (Hook + Script)",
    briefId: "Brand minuman butuh 7 konten TikTok/Reels seminggu. Buat: hook + script per konten (masing-masing <60 detik), shot list, CTA, dan jadwal posting + 1 contoh video/link draft + tabel ekspektasi metrics.",
    deliverableSpec: { modes: ["DOCUMENT", "LINK", "IMAGE"], minArtifacts: 2, constraints: "Wajib 7 script + 1 draft" },
    rubric: [
      { id: "hook", labelId: "Kekuatan hook 3 detik", weight: 0.35 },
      { id: "variasi", labelId: "Variasi format & sudut", weight: 0.3 },
      { id: "eksekusi", labelId: "Kelayakan produksi 1 orang", weight: 0.35 },
    ],
    skkniUnitCode: "M.70MKT00.015.1", kkniLevel: 5, difficulty: 2, estimatedMin: 150, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-copy", slug: "copy-landing-umkm-ctr", roleId: "copywriter",
    titleId: "Copy Landing UMKM + 3 Varian Headline",
    briefId: "Laundry kiloan mau landing page. Tulis: headline + sub + 3 section benefit + FAQ + CTA + 3 varian headline untuk A/B test (masing-masing dengan hipotesis) + alasan pilihan kata.",
    deliverableSpec: { modes: ["DOCUMENT"], minArtifacts: 1, constraints: "Wajib 3 varian + hipotesis" },
    rubric: [
      { id: "pesan", labelId: "Kejelasan pesan & CTA", weight: 0.4 },
      { id: "varian", labelId: "Kualitas varian A/B test", weight: 0.35 },
      { id: "nada", labelId: "Kesesuaian nada brand lokal", weight: 0.25 },
    ],
    skkniUnitCode: "M.73ADV00.024.1", kkniLevel: 5, difficulty: 2, estimatedMin: 120, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-graphic", slug: "graphic-kit-feed-umkm", roleId: "graphic-designer",
    titleId: "Kit 9 Feed Instagram + Sistem Visual",
    briefId: "Kopi susu baru butuh 9 feed launching. Buat: sistem visual 1 halaman (warna, font, grid, gaya foto) + 9 desain (link Figma/Canva + export) + caption singkat per posting + file serah terima (naming + versi).",
    deliverableSpec: { modes: ["IMAGE", "LINK", "DOCUMENT"], minArtifacts: 2, constraints: "Wajib sistem visual + 9 feed" },
    rubric: [
      { id: "sistem", labelId: "Konsistensi sistem visual", weight: 0.35 },
      { id: "karya", labelId: "Kualitas 9 feed", weight: 0.4 },
      { id: "serah", labelId: "Kerapian serah terima", weight: 0.25 },
    ],
    skkniUnitCode: "M.70MKT00.016.1", kkniLevel: 5, difficulty: 2, estimatedMin: 180, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-seo", slug: "seo-audit-umkm-10-keyword", roleId: "seo-specialist",
    titleId: "Audit SEO + Rencana 10 Keyword",
    briefId: "Website katering tidak muncul di Google. Buat audit 2 halaman (teknis: speed, meta, struktur + konten gap) + spreadsheet 10 keyword (volume, intent, difficulty, prioritas) + 4 brief artikel + timeline 90 hari.",
    deliverableSpec: { modes: ["DOCUMENT", "SPREADSHEET"], minArtifacts: 2, constraints: "Wajib 10 keyword + 4 brief" },
    rubric: [
      { id: "audit", labelId: "Ketepatan temuan audit", weight: 0.35 },
      { id: "keyword", labelId: "Kualitas riset keyword", weight: 0.4 },
      { id: "rencana", labelId: "Realisme rencana 90 hari", weight: 0.25 },
    ],
    skkniUnitCode: "M.70MKT00.013.1", kkniLevel: 5, difficulty: 3, estimatedMin: 180, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-motion", slug: "motion-iklan-15-detik", roleId: "motion-designer",
    titleId: "Iklan Motion 15 Detik + Storyboard",
    briefId: "Promo laundry: buat storyboard 6 frame + iklan 15 detik (link video/draft) + file project terstruktur + catatan render (resolusi, codec, ukuran) + 2 varian CTA end-card.",
    deliverableSpec: { modes: ["LINK", "IMAGE", "DOCUMENT"], minArtifacts: 2, constraints: "Wajib storyboard + video/draft" },
    rubric: [
      { id: "cerita", labelId: "Kekuatan storyboard & pacing", weight: 0.35 },
      { id: "teknis", labelId: "Kualitas eksekusi motion", weight: 0.4 },
      { id: "siap", labelId: "Kesiapan file & render", weight: 0.25 },
    ],
    skkniUnitCode: "M.70MKT00.017.1", kkniLevel: 5, difficulty: 3, estimatedMin: 240, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-abm", slug: "abm-relaunch-sambal", roleId: "assistant-brand-manager",
    titleId: "Relaunch Sambal Botol + P&L Sederhana",
    briefId: "Sambal botol stagnan. Buat: positioning 1 kalimat + 3 inisiatif (kemasan, distribusi, promo) + spreadsheet P&L sederhana (COGS, margin, promo cost) + timeline 6 bulan + 1 halaman risiko.",
    deliverableSpec: { modes: ["DOCUMENT", "SPREADSHEET"], minArtifacts: 2, constraints: "Wajib P&L + timeline" },
    rubric: [
      { id: "posisi", labelId: "Ketajaman positioning", weight: 0.3 },
      { id: "angka", labelId: "Kualitas P&L & asumsi", weight: 0.4 },
      { id: "eksekusi", labelId: "Kelayakan rencana 6 bulan", weight: 0.3 },
    ],
    skkniUnitCode: "M.70MKT00.018.1", kkniLevel: 6, difficulty: 4, estimatedMin: 180, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-pr", slug: "pr-siaran-pers-buka-cabang", roleId: "pr-specialist",
    titleId: "Siaran Pers + Daftar Media 20 Kontak",
    briefId: "Klinik gigi buka cabang ke-5. Tulis siaran pers 1 halaman (5W1H, kutipan, boilerplate) + daftar 20 media/kontak (nama, deskripsi beat, alasan cocok) + plan distribusi 7 hari + 3 angle cadangan.",
    deliverableSpec: { modes: ["DOCUMENT", "SPREADSHEET"], minArtifacts: 2, constraints: "Wajib 20 kontak + plan" },
    rubric: [
      { id: "naskah", labelId: "Kualitas naskah pers", weight: 0.4 },
      { id: "daftar", labelId: "Ketepatan targeting media", weight: 0.35 },
      { id: "distribusi", labelId: "Kelayakan plan distribusi", weight: 0.25 },
    ],
    skkniUnitCode: "M.70MKT00.019.1", kkniLevel: 5, difficulty: 3, estimatedMin: 120, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-video", slug: "video-podcast-1-episode", roleId: "video-editor",
    titleId: "Edit Podcast 30 Menit → Episode + 3 Shorts",
    briefId: "Dari footage mentah (link): hasilkan timeline edit + 1 episode 30 menit (link draft) + 3 shorts vertikal (hook <3s) + chapter + thumbnail 2 varian + checklist audio (loudness, noise).",
    deliverableSpec: { modes: ["LINK", "IMAGE", "DOCUMENT"], minArtifacts: 2, constraints: "Wajib episode + 3 shorts" },
    rubric: [
      { id: "pacing", labelId: "Kualitas pacing & struktur", weight: 0.4 },
      { id: "shorts", labelId: "Kekuatan 3 shorts", weight: 0.35 },
      { id: "audio", labelId: "Kualitas audio & packaging", weight: 0.25 },
    ],
    skkniUnitCode: "M.70MKT00.020.1", kkniLevel: 5, difficulty: 3, estimatedMin: 240, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-strategist", slug: "strategist-repurpose-90-hari", roleId: "content-strategist",
    titleId: "Strategi Repurpose 90 Hari 1→10",
    briefId: "Brand punya 1 webinar/bulan. Buat matriks repurpose (1 webinar → 10 turunan: shorts, carousel, artikel, email) + kalender 90 hari + spreadsheet prioritas (effort vs impact) + 2 contoh eksekusi.",
    deliverableSpec: { modes: ["DOCUMENT", "SPREADSHEET", "LINK"], minArtifacts: 2, constraints: "Wajib matriks + 2 contoh" },
    rubric: [
      { id: "sistem", labelId: "Kecerdasan sistem repurpose", weight: 0.4 },
      { id: "prioritas", labelId: "Ketepatan prioritas effort/impact", weight: 0.3 },
      { id: "contoh", labelId: "Kualitas contoh eksekusi", weight: 0.3 },
    ],
    skkniUnitCode: "M.70MKT00.021.1", kkniLevel: 5, difficulty: 3, estimatedMin: 150, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-kol", slug: "kol-kampanye-skincare-20jt", roleId: "kol-specialist",
    titleId: "Kampanye KOL Rp20 Juta + Kontrak",
    briefId: "Skincare budget Rp20jt. Buat: longlist 15 KOL (tier, rate, ER, alasan) + alokasi budget + draft kontrak 1 halaman (deliverable, timeline, FTC disclosure, klausul revisi) + plan pengukuran (kode voucher/UTM).",
    deliverableSpec: { modes: ["SPREADSHEET", "DOCUMENT"], minArtifacts: 2, constraints: "Wajib kontrak + tracking" },
    rubric: [
      { id: "seleksi", labelId: "Ketepatan seleksi KOL", weight: 0.35 },
      { id: "budget", labelId: "Efisiensi alokasi budget", weight: 0.3 },
      { id: "kontrak", labelId: "Kelengkapan kontrak & disclosure", weight: 0.35 },
    ],
    skkniUnitCode: "M.70MKT00.022.1", kkniLevel: 5, difficulty: 3, estimatedMin: 150, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-artdir", slug: "artdir-konsep-kampanye-ramadan", roleId: "junior-art-director",
    titleId: "Konsep Kampanye Ramadan + Direct 2 Desainer",
    briefId: "Sirup butuh kampanye Ramadan. Buat: big idea 1 kalimat + moodboard (link) + 3 key visual direction + brief tertulis untuk 2 desainer (do/don't, deadline, format) + cara menilai hasil (kriteria 5 poin).",
    deliverableSpec: { modes: ["DOCUMENT", "LINK", "IMAGE"], minArtifacts: 2, constraints: "Wajib brief desainer + kriteria nilai" },
    rubric: [
      { id: "ide", labelId: "Kekuatan big idea", weight: 0.35 },
      { id: "brief", labelId: "Kejelasan brief ke desainer", weight: 0.35 },
      { id: "penilaian", labelId: "Kualitas kriteria penilaian", weight: 0.3 },
    ],
    skkniUnitCode: "M.70MKT00.023.1", kkniLevel: 5, difficulty: 4, estimatedMin: 180, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-uxr", slug: "uxr-riset-onboarding-fintech", roleId: "ux-researcher",
    titleId: "Riset Onboarding Fintech + Insight→Rekomendasi",
    briefId: "Aplikasi pinjol legal drop-off onboarding 60%. Buat: research plan (tujuan, 5 partisipan, metode) + panduan wawancara 8 pertanyaan + temuan sintetis (affinity: 3 tema) + 5 rekomendasi desain berperingkat + 1 halaman batasan riset.",
    deliverableSpec: { modes: ["DOCUMENT"], minArtifacts: 1, constraints: "Wajib 8 pertanyaan + 3 tema + 5 rekomendasi" },
    rubric: [
      { id: "metode", labelId: "Ketepatan metode & pertanyaan", weight: 0.35 },
      { id: "sintesis", labelId: "Kualitas sintesis temuan", weight: 0.35 },
      { id: "dampak", labelId: "Kelayakan rekomendasi desain", weight: 0.3 },
    ],
    skkniUnitCode: "M.70MKT00.024.1", kkniLevel: 6, difficulty: 4, estimatedMin: 180, maxRevisions: 3, status: "PUBLISHED",
  },
];
