import type { Mission } from "./missions";

// Tech & Product (14) + Future & AI (7) — 1 misi inti per profesi.
export const MISSIONS_TECH: Mission[] = [
  {
    id: "seed-frontend-landing-audit", slug: "frontend-audit-performa-landing", roleId: "frontend-developer",
    titleId: "Audit Performa Landing Page + Perbaiki LCP",
    briefId: "Landing page UMKM skor Lighthouse 52, LCP 4.8s. Diberikan repo starter + screenshot trace. Kirim: 1) code patch (snippet/link repo), 2) dokumen audit (temuan + prioritas + estimasi gain), 3) screenshot before/after.",
    deliverableSpec: { modes: ["CODE", "DOCUMENT", "IMAGE", "LINK"], minArtifacts: 2, constraints: "Wajib LCP before/after + patch" },
    rubric: [
      { id: "diagnosis", labelId: "Ketepatan diagnosis bottleneck", weight: 0.3 },
      { id: "solusi", labelId: "Kualitas solusi teknis", weight: 0.4 },
      { id: "laporan", labelId: "Kejelasan laporan audit", weight: 0.3 },
    ],
    skkniUnitCode: "J.620100.001.01", kkniLevel: 6, difficulty: 3, estimatedMin: 180, maxRevisions: 5, status: "PUBLISHED",
  },
  {
    id: "seed-backend-api", slug: "backend-api-kasir-umkm", roleId: "backend-developer",
    titleId: "API Kasir UMKM + Skema Database",
    briefId: "Warung kelontong butuh API kasir: produk, transaksi, stok. Rancang skema database (3–5 tabel + relasi), tulis 3 endpoint (daftar produk, buat transaksi, kurangi stok) dalam framework pilihan, sertakan penjelasan keputusan desain + cara handle race condition stok.",
    deliverableSpec: { modes: ["CODE", "DOCUMENT"], minArtifacts: 2, constraints: "Wajib skema + 3 endpoint + race-condition note" },
    rubric: [
      { id: "skema", labelId: "Ketepatan desain skema data", weight: 0.35 },
      { id: "api", labelId: "Kualitas implementasi endpoint", weight: 0.4 },
      { id: "edge", labelId: "Penanganan edge case (stok ganda)", weight: 0.25 },
    ],
    skkniUnitCode: "J.620100.002.01", kkniLevel: 6, difficulty: 4, estimatedMin: 180, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-qa", slug: "qa-test-plan-checkout", roleId: "qa-engineer",
    titleId: "Test Plan Fitur Checkout + Kasus Uji",
    briefId: "Fitur checkout marketplace akan rilis: keranjang, voucher, QRIS. Buat test plan 1–2 halaman (scope, prioritas risiko) + 15 test case (positif, negatif, edge: voucher kadaluarsa, double-callback) + 1 script automation (Playwright/Cypress) untuk happy path.",
    deliverableSpec: { modes: ["DOCUMENT", "CODE"], minArtifacts: 2, constraints: "Wajib 15 TC + 1 script automation" },
    rubric: [
      { id: "cakupan", labelId: "Kelengkapan cakupan uji", weight: 0.4 },
      { id: "prioritas", labelId: "Ketepatan prioritas risiko", weight: 0.3 },
      { id: "otomasi", labelId: "Kualitas script automation", weight: 0.3 },
    ],
    skkniUnitCode: "J.620100.004.01", kkniLevel: 6, difficulty: 3, estimatedMin: 150, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-devops", slug: "devops-pipeline-ci-cd", roleId: "devops-engineer",
    titleId: "Pipeline CI/CD + Runbook Insiden",
    briefId: "Startup deploy manual via ZIP ke VPS — sering down. Rancang pipeline CI/CD (lint → test → build → deploy) sebagai file config + runbook 1 halaman (rollback, cek log, kontak darurat) + estimasi biaya infra/bulan.",
    deliverableSpec: { modes: ["CODE", "DOCUMENT"], minArtifacts: 2, constraints: "Wajib config pipeline + runbook + costing" },
    rubric: [
      { id: "pipeline", labelId: "Kelengkapan pipeline", weight: 0.4 },
      { id: "runbook", labelId: "Kegunaan runbook saat insiden", weight: 0.35 },
      { id: "biaya", labelId: "Realisme estimasi biaya", weight: 0.25 },
    ],
    skkniUnitCode: "SKKNI-2023-102-U2", kkniLevel: 6, difficulty: 4, estimatedMin: 180, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-mobile", slug: "mobile-aplikasi-kasir-offline", roleId: "mobile-developer",
    titleId: "Aplikasi Kasir Offline-First (Prototype)",
    briefId: "Pasar tradisional sinyal buruk. Buat prototype Flutter: daftar produk, keranjang offline (local storage), sinkron saat online. Kirim snippet kode inti + dokumen keputusan (state management, strategi sync) + screenshot/link demo.",
    deliverableSpec: { modes: ["CODE", "DOCUMENT", "IMAGE", "LINK"], minArtifacts: 2, constraints: "Wajib offline-first + strategi sync" },
    rubric: [
      { id: "fungsi", labelId: "Fungsi offline-first berjalan", weight: 0.4 },
      { id: "arsitektur", labelId: "Kualitas keputusan arsitektur", weight: 0.3 },
      { id: "ux", labelId: "Kejelasan alur kasir", weight: 0.3 },
    ],
    skkniUnitCode: "J.620100.005.01", kkniLevel: 6, difficulty: 4, estimatedMin: 240, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-data-analyst", slug: "data-analyst-dashboard-q3", roleId: "data-analyst",
    titleId: "Dashboard Penjualan Q3 + Insight Top-SKU",
    briefId: "Direksi butuh dashboard penjualan Q3 dari 3 channel (offline, marketplace, reseller). Buat spreadsheet model + dokumen 1 halaman: top-SKU, anomali, 3 rekomendasi stok/promo + link dashboard bila ada.",
    deliverableSpec: { modes: ["SPREADSHEET", "DOCUMENT", "LINK"], minArtifacts: 2, constraints: "Wajib pivot channel×SKU + 3 rekomendasi" },
    rubric: [
      { id: "akurasi", labelId: "Akurasi agregasi & model data", weight: 0.35 },
      { id: "visual", labelId: "Kejelasan visual & dashboard", weight: 0.3 },
      { id: "rekomendasi", labelId: "Ketajaman rekomendasi bisnis", weight: 0.35 },
    ],
    skkniUnitCode: "J.620100.003.01", kkniLevel: 6, difficulty: 2, estimatedMin: 120, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-data-engineer", slug: "data-engineer-pipeline-harian", roleId: "data-engineer",
    titleId: "Pipeline Data Harian + Data Quality Check",
    briefId: "Data transaksi 3 cabang dikirim CSV tiap malam, format berantakan. Rancang pipeline harian (ingest → validasi → warehouse table) sebagai diagram + script + 5 data-quality rules (duplikat, null, format tanggal, outlier omzet) + cara alerting.",
    deliverableSpec: { modes: ["DOCUMENT", "CODE"], minArtifacts: 2, constraints: "Wajib diagram + 5 DQ rules" },
    rubric: [
      { id: "desain", labelId: "Kelengkapan desain pipeline", weight: 0.4 },
      { id: "dq", labelId: "Ketepatan quality rules", weight: 0.35 },
      { id: "operasi", labelId: "Kesiapan monitoring/alerting", weight: 0.25 },
    ],
    skkniUnitCode: "J.620100.003.02", kkniLevel: 6, difficulty: 4, estimatedMin: 180, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-itba", slug: "itba-brd-modul-stok", roleId: "it-business-analyst",
    titleId: "BRD Modul Stok + UAT Plan",
    briefId: "Toko punya 4 cabang, stok sering selisih. Tulis BRD 2–3 halaman (as-is, to-be, 8 functional requirements + acceptance criteria) + UAT plan 10 skenario + matriks RACI singkat.",
    deliverableSpec: { modes: ["DOCUMENT"], minArtifacts: 1, constraints: "Wajib 8 FR + AC + 10 skenario UAT" },
    rubric: [
      { id: "kebutuhan", labelId: "Kelengkapan & kejelasan requirements", weight: 0.4 },
      { id: "uat", labelId: "Kualitas UAT plan", weight: 0.35 },
      { id: "komunikasi", labelId: "Keterbacaan untuk bisnis & dev", weight: 0.25 },
    ],
    skkniUnitCode: "SKKNI-PM-U1", kkniLevel: 6, difficulty: 3, estimatedMin: 150, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-apm", slug: "apm-prd-qris-edgecases", roleId: "associate-product-manager",
    titleId: "PRD Fitur Pembayaran QRIS + Edge Cases",
    briefId: "Buat PRD 3–5 halaman untuk fitur QRIS di aplikasi kasir UMKM: latar, user stories, acceptance criteria, edge cases (timeout, double-callback, refund), metrics + link mockup bila ada.",
    deliverableSpec: { modes: ["DOCUMENT", "LINK"], minArtifacts: 1, constraints: "Wajib AC + edge cases + metrics" },
    rubric: [
      { id: "prd", labelId: "Kelengkapan PRD & AC", weight: 0.4 },
      { id: "edge", labelId: "Cakupan edge cases pembayaran", weight: 0.3 },
      { id: "metrics", labelId: "Ketepatan metrics & rollout", weight: 0.3 },
    ],
    skkniUnitCode: "SKKNI-PM-U1", kkniLevel: 6, difficulty: 2, estimatedMin: 120, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-network", slug: "network-topologi-kantor-baru", roleId: "network-engineer",
    titleId: "Topologi Jaringan Kantor 3 Lantai + Troubleshooting",
    briefId: "Kantor baru 3 lantai, 80 user. Buat diagram topologi (router, switch, AP, VLAN tamu/karyawan) + daftar perangkat + budget + 1 dokumen troubleshooting (internet lambat di lantai 2: langkah diagnosis berurutan).",
    deliverableSpec: { modes: ["DOCUMENT", "IMAGE"], minArtifacts: 2, constraints: "Wajib diagram + langkah diagnosis" },
    rubric: [
      { id: "topologi", labelId: "Ketepatan desain topologi", weight: 0.4 },
      { id: "budget", labelId: "Realisme budget perangkat", weight: 0.25 },
      { id: "troubleshoot", labelId: "Logika troubleshooting", weight: 0.35 },
    ],
    skkniUnitCode: "J.620100.006.01", kkniLevel: 5, difficulty: 4, estimatedMin: 150, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-cyber", slug: "cyber-soc-shift-report", roleId: "cybersecurity-analyst",
    titleId: "Laporan Shift SOC + Triase 3 Alert",
    briefId: "Diberikan 3 alert SIEM anonim (phishing login, malware beacon, port scan). Tulis laporan shift: klasifikasi tiap alert (TP/FP + alasan), prioritas, langkah containment per alert, dan 2 rekomendasi hardening.",
    deliverableSpec: { modes: ["DOCUMENT"], minArtifacts: 1, constraints: "Wajib klasifikasi + containment tiap alert" },
    rubric: [
      { id: "triase", labelId: "Ketepatan triase & klasifikasi", weight: 0.4 },
      { id: "respons", labelId: "Kualitas langkah containment", weight: 0.35 },
      { id: "hardening", labelId: "Nilai rekomendasi hardening", weight: 0.25 },
    ],
    skkniUnitCode: "SKKNI-CYB-U2", kkniLevel: 6, difficulty: 4, estimatedMin: 150, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-game", slug: "game-prototype-hypercasual", roleId: "game-developer",
    titleId: "Prototype Hypercasual + Tuning 60fps di HP Kentang",
    briefId: "Buat GDD 1 halaman + prototype playable (link build/video) game hypercasual: 1 core loop, 3 level tuning, dan catatan optimasi agar 60fps di HP Rp1 jutaan (draw call, texture, object pooling).",
    deliverableSpec: { modes: ["DOCUMENT", "LINK", "IMAGE"], minArtifacts: 2, constraints: "Wajib playable + catatan optimasi" },
    rubric: [
      { id: "fun", labelId: "Kejelasan core loop & tuning", weight: 0.35 },
      { id: "teknis", labelId: "Kualitas optimasi performa", weight: 0.4 },
      { id: "presentasi", labelId: "Kualitas GDD & demo", weight: 0.25 },
    ],
    skkniUnitCode: "J.620100.007.01", kkniLevel: 5, difficulty: 4, estimatedMin: 240, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-sre", slug: "sre-postmortem-downtime", roleId: "site-reliability-engineer",
    titleId: "Postmortem Downtime 45 Menit + SLO",
    briefId: "Checkout down 45 menit saat flash sale. Tulis postmortem blameless (timeline, root cause, 5 whys) + definisi 2 SLO + 3 action items prioritas + dashboard monitoring yang perlu ditambah.",
    deliverableSpec: { modes: ["DOCUMENT"], minArtifacts: 1, constraints: "Wajib 5 whys + 2 SLO + 3 action" },
    rubric: [
      { id: "analisis", labelId: "Kedalaman analisis root cause", weight: 0.4 },
      { id: "slo", labelId: "Ketepatan definisi SLO", weight: 0.3 },
      { id: "aksi", labelId: "Kelayakan action items", weight: 0.3 },
    ],
    skkniUnitCode: "SKKNI-2023-102-U3", kkniLevel: 6, difficulty: 5, estimatedMin: 150, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-solarch", slug: "solarch-proposal-erp", roleId: "solutions-architect",
    titleId: "Proposal Solusi ERP untuk Distributor",
    briefId: "Distributor 200 karyawan mau ERP. Buat proposal 3 halaman: requirement mapping, 2 opsi arsitektur (cloud vs hybrid) + pro-kontra + TCO 3 tahun, rencana migrasi fase, dan risiko + mitigasi.",
    deliverableSpec: { modes: ["DOCUMENT", "SPREADSHEET"], minArtifacts: 1, constraints: "Wajib TCO + rencana migrasi" },
    rubric: [
      { id: "mapping", labelId: "Ketepatan mapping kebutuhan", weight: 0.35 },
      { id: "arsitektur", labelId: "Kualitas opsi arsitektur & TCO", weight: 0.4 },
      { id: "risiko", labelId: "Kelengkapan risiko & migrasi", weight: 0.25 },
    ],
    skkniUnitCode: "SKKNI-2023-102-U4", kkniLevel: 6, difficulty: 5, estimatedMin: 180, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-ai-eng", slug: "aieng-rag-cs-kopi", roleId: "ai-engineer",
    titleId: "Chatbot RAG CS Kedai Kopi + Evaluasi",
    briefId: "Kedai kopi punya 40 halaman SOP/menu. Bangun chatbot RAG: pipeline ingest-chunk-retrieve-generate + 10 pertanyaan uji + tabel evaluasi (jawaban benar/ngawur) + 1 halaman batasan & biaya inferensi.",
    deliverableSpec: { modes: ["CODE", "DOCUMENT", "LINK"], minArtifacts: 2, constraints: "Wajib 10 QA eval + costing" },
    rubric: [
      { id: "pipeline", labelId: "Kelengkapan pipeline RAG", weight: 0.4 },
      { id: "eval", labelId: "Kualitas evaluasi & anti-halusinasi", weight: 0.35 },
      { id: "operasi", labelId: "Realisme biaya & batasan", weight: 0.25 },
    ],
    skkniUnitCode: "SKKNI-2020-299-U3", kkniLevel: 6, difficulty: 5, estimatedMin: 240, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-data-sci", slug: "datasci-churn-model", roleId: "data-scientist",
    titleId: "Model Prediksi Churn + Rekomendasi Intervensi",
    briefId: "Provider internet punya dataset churn anonim. Buat notebook ringkas: EDA 1 halaman, 2 model baseline + perbandingan metrik (precision/recall), feature importance, dan 3 rekomendasi intervensi berbasis segmen.",
    deliverableSpec: { modes: ["CODE", "DOCUMENT"], minArtifacts: 2, constraints: "Wajib baseline + metrik + intervensi" },
    rubric: [
      { id: "eda", labelId: "Kualitas eksplorasi data", weight: 0.3 },
      { id: "model", labelId: "Ketepatan modeling & evaluasi", weight: 0.4 },
      { id: "bisnis", labelId: "Nilai rekomendasi bisnis", weight: 0.3 },
    ],
    skkniUnitCode: "SKKNI-2020-299-U2", kkniLevel: 6, difficulty: 5, estimatedMin: 240, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-ai-auto", slug: "aiauto-otomasi-invoice-wa", roleId: "ai-automation-specialist",
    titleId: "Otomasi Invoice → Rekap → Notif WA",
    briefId: "UMKM terima 50 invoice foto/minggu via WA. Rancang workflow automation (n8n/Zapier): ekstrak → validasi → rekap Sheets → notif. Kirim diagram alur + tabel tools & biaya + 5 edge cases (foto blur, duplikat, nominal aneh) + cara handle-nya.",
    deliverableSpec: { modes: ["DOCUMENT", "LINK"], minArtifacts: 1, constraints: "Wajib 5 edge cases + costing" },
    rubric: [
      { id: "alur", labelId: "Kelengkapan alur otomasi", weight: 0.4 },
      { id: "edge", labelId: "Penanganan edge cases", weight: 0.35 },
      { id: "biaya", labelId: "Realisme tools & biaya", weight: 0.25 },
    ],
    skkniUnitCode: "SKKNI-2020-299-U4", kkniLevel: 5, difficulty: 4, estimatedMin: 150, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-cloud", slug: "cloud-migrasi-tco", roleId: "cloud-solutions-architect",
    titleId: "Rencana Migrasi Cloud + Kalkulasi TCO",
    briefId: "Perusahaan punya 10 VM on-prem. Buat rencana migrasi 3 fase (assess, pilot, cutover) + spreadsheet TCO on-prem vs cloud 3 tahun + strategi rollback + checklist keamanan.",
    deliverableSpec: { modes: ["DOCUMENT", "SPREADSHEET"], minArtifacts: 2, constraints: "Wajib TCO 3 tahun + rollback" },
    rubric: [
      { id: "fase", labelId: "Kelayakan tahapan migrasi", weight: 0.35 },
      { id: "tco", labelId: "Akurasi kalkulasi TCO", weight: 0.4 },
      { id: "aman", labelId: "Kelengkapan keamanan & rollback", weight: 0.25 },
    ],
    skkniUnitCode: "SKKNI-2023-102-U1", kkniLevel: 6, difficulty: 5, estimatedMin: 180, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-esg", slug: "esg-laporan-emisi-pabrik", roleId: "esg-analyst",
    titleId: "Inventarisasi Emisi 3 Pabrik + Rencana Penurunan",
    briefId: "Grup manufaktur punya 3 pabrik. Dari data konsumsi energi/BBM anonim, buat spreadsheet inventarisasi emisi (scope 1+2) + dokumen 2 halaman: hotspot, 4 inisiatif penurunan + biaya & dampak, dan roadmap pelaporan.",
    deliverableSpec: { modes: ["SPREADSHEET", "DOCUMENT"], minArtifacts: 2, constraints: "Wajib scope 1+2 + 4 inisiatif" },
    rubric: [
      { id: "data", labelId: "Ketepatan inventarisasi", weight: 0.4 },
      { id: "inisiatif", labelId: "Kelayakan inisiatif penurunan", weight: 0.35 },
      { id: "roadmap", labelId: "Kejelasan roadmap pelaporan", weight: 0.25 },
    ],
    skkniUnitCode: "SKKNI-ESG-U1", kkniLevel: 6, difficulty: 4, estimatedMin: 180, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-robotics", slug: "robotics-lengan-sortir", roleId: "robotics-engineer",
    titleId: "Konsep Lengan Robot Sortir Paket + BOM",
    briefId: "Gudang e-commerce butuh lengan robot sortir paket <2kg. Buat dokumen konsep (DOF, payload, sensor, safety) + BOM + estimasi biaya + 5 risiko + video/link referensi implementasi serupa.",
    deliverableSpec: { modes: ["DOCUMENT", "SPREADSHEET", "LINK"], minArtifacts: 2, constraints: "Wajib BOM + safety" },
    rubric: [
      { id: "konsep", labelId: "Kelayakan konsep teknik", weight: 0.4 },
      { id: "bom", labelId: "Kelengkapan BOM & biaya", weight: 0.3 },
      { id: "aman", labelId: "Cakupan safety & risiko", weight: 0.3 },
    ],
    skkniUnitCode: "SKKNI-2020-300-U2", kkniLevel: 6, difficulty: 5, estimatedMin: 180, maxRevisions: 3, status: "PUBLISHED",
  },
  {
    id: "seed-iot", slug: "iot-monitoring-suhu-coldchain", roleId: "embedded-iot-engineer",
    titleId: "Sistem Monitoring Suhu Cold-Chain + Alert",
    briefId: "Distributor vaksin butuh monitoring suhu 2–8°C di 5 titik. Rancang: pilihan sensor/MCU/konektivitas + diagram + firmware pseudocode baca-kirim-sleep + aturan alert + estimasi daya & biaya per titik.",
    deliverableSpec: { modes: ["DOCUMENT", "CODE"], minArtifacts: 2, constraints: "Wajib daya + alert rules" },
    rubric: [
      { id: "desain", labelId: "Ketepatan pemilihan hardware", weight: 0.35 },
      { id: "firmware", labelId: "Kualitas logika firmware", weight: 0.35 },
      { id: "operasi", labelId: "Realisme daya, biaya & alert", weight: 0.3 },
    ],
    skkniUnitCode: "SKKNI-2020-300-U1", kkniLevel: 6, difficulty: 5, estimatedMin: 180, maxRevisions: 3, status: "PUBLISHED",
  },
];
